FROM mcr.microsoft.com/mssql-tools:latest

WORKDIR /init-scripts

COPY init-scripts/init-db.sh ./init-db.sh
COPY init-scripts/init-db.sql ./init-db.sql
COPY init-scripts/insert-default-data.sql ./insert-default-data.sql
COPY init-scripts/wait-for-it.sh ./wait-for-it.sh

RUN chmod +x ./init-db.sh
RUN chmod +x ./wait-for-it.sh

CMD ["./init-db.sh"] 